services:
  app:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  # Redis можно оставить внешним (Upstash) или добавить свой
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
