name: Hantavirus Auto Update
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r parser/requirements.txt

      - name: Run Parser
        run: python parser/parser.py

      - name: Commit and Push
        run: |
          git config --global user.name "Hantavirus-Bot-Bot"
          git config --global user.name "github-actions[bot]"
          git add data/stats.json
          git commit -m "📊 Auto-update stats: $(date)" || exit 0
          git push